# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [ ]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [6]:
res1 = np.array([1, 2, 3, 4, 5])

print(res1)

[1 2 3 4 5]


In [7]:
res2 = np.arange(1, 6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [8]:
res3 = np.random.randint(1, 101, size=(3, 5))

print(res3)

[[19 61 88 51 45]
 [74  4 97 78 36]
 [39 19 66 32 66]]


### Task 3

Print the first row of array `res3`.

In [9]:
print(res3[0])

[19 61 88 51 45]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [10]:
last_column = res3[:, -1]
print(last_column)

[45 36 66]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [11]:
# Min
res_min = np.min(res3[:, 1])

print('min =', res_min)

min = 4


In [13]:
# Max
res_max = np.max(res3[:, 1])

print('max =', res_max)

max = 61


In [14]:
# Sum
res_sum = np.sum(res3[:, 1])

print('sum =', res_sum)

sum = 84


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [16]:
x = np.arange(0, 1 + 0.1, 0.1)
f_x = np.exp(2 * x)

print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [18]:
url = "https://web.stanford.edu/class/cs102/datasets/Titanic.csv"
df = pd.read_csv(url)
print(df.head())

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  Southampton      yes  
3  53.1000  Southampton      yes  
4   8.0500  Southampton       no  


### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [19]:
print("Columns present in the data frame:")
print(df.columns)

Columns present in the data frame:
Index(['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked',
       'survived'],
      dtype='object')


In [20]:
print("\nFirst ten rows of data:")
print(df.head(10))


First ten rows of data:
        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg 

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [26]:
df['full name'] = df['first'] + ' ' + df['last']

print(df.head())

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   

      fare     embarked survived  \
0   7.2500  Southampton       no   
1  71.2833    Cherbourg      yes   
2   7.9250  Southampton      yes   
3  53.1000  Southampton      yes   
4   8.0500  Southampton       no   

                                           full name  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                          

### Task 10

Remove the two original columns - last, first.

In [27]:
df = df.drop(columns=['last', 'first'])
print(df.head())

  gender   age  class     fare     embarked survived  \
0      M  22.0      3   7.2500  Southampton       no   
1      F  38.0      1  71.2833    Cherbourg      yes   
2      F  26.0      3   7.9250  Southampton      yes   
3      F  35.0      1  53.1000  Southampton      yes   
4      M  35.0      3   8.0500  Southampton       no   

                                           full name  
0                             Mr. Owen Harris Braund  
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  
2                               Miss Laina Heikkinen  
3        Mrs. Jacques Heath (Lily May Peel) Futrelle  
4                            Mr. William Henry Allen  


### Task 11

Calculate the total number of survivors in the dataset.

In [33]:
total_survivors = len(df[df['survived'] == 'yes'])
print("Total number of survivors:", total_survivors)

Total number of survivors: 342
